# goal

[comment]: <>  image:https://travis-ci.org/lesunb/goald.svg?branch=master["Build Status", link="https://travis-ci.org/lesunb/goald"]
[comment]: <>  image:https://coveralls.io/repos/github/lesunb/goald/badge.svg?branch=master["Coverage Status", link="https://coveralls.io/repos/github/lesunb/goald?branch=master"]
image:https://api.bintray.com/packages/lesunb/goald/goald/images/download.svg[link="https://bintray.com/lesunb/goald/goald/_latestVersion"]
[comment]: <>  image:https://codeclimate.com/github/lesunb/goald/badges/issue_count.svg["Issues", link="https://codeclimate.com/github/lesunb/goald"]
[comment]: <>  image:https://ci.appveyor.com/api/projects/status/mxxhw5ahlcdje6p6?svg=true["appveyor", link="https://ci.appveyor.com/project/gabrielsr/goald"]

Intro 
=====

Goald is an effort to create a Goal-Driven Deployment Framework. In your long term vision we imagine a platform in which:

developers:: 
 contribute with components that are means of implementing user goals.

users:: 
 make requests to the computing environment with goals they want to achieve in that environment.

the computer environment:: 
 deploy the known components that allow for goal achievement at that environment making the goals achievable. It also looks for new users goals, new components, and changes in the environment.
 

https://github.com/lesunb/goald/wiki/Goald[See More]

= Setup

== JDK8 the compiler and virtual machine

Install JDK8: 
	http://www.oracle.com/technetwork/java/javase/downloads/index.html

	
== Eclipse (Mars) the IDE
	http://www.eclipse.org/downloads/packages/eclipse-ide-java-developers/mars2

	
== Maven: Dependency Manager and Build	

It should come with Eclipse, don't worry.


= Building and Running GOALD

 * clone the repo: 
  $ git clone https://github.com/lesunb/goald/ 

== Importing project into Eclipse

 * Open Eclipse
 * File > Import > Existing Project
 * Find the folder where you cloned goald project
 * Accept the defaults

== Run Tests into Eclipse

 * Right click in the goald-core project
 * Run As > JUnit Tests
 
 
== Run TAS Example (Timeline) ==

 * Right click in the tele-assistance-case-study project
 * Run As > Run Configurations > Java Application
 * Choose goald.evaluation.tas.TASMain as 'Main class'
 * In the tab 'Arguments', edit 'VM arguments:' with "--add-opens java.base/java.lang=ALL-UNNAMED"
 * The evaluation experiment should init and you should see logs into the console of Eclipse.
 * Final result should be created at tele-assistance-case-study > result
 * Evaluation param can be changed at the class
 
== Run Scalability Evaluation

 * Right click in the evaluation project
 * Run As > Java Application
 * Choose EvaluationMain class
 * The evaluation experiment should init and you should see logs into the console of Eclipse.
 * Final result should be created at evaluation > result
 * Evaluation param can be changed at the class
 
goald.evaluation.plans.CreateExperimentsToEvaluateScalabilityOverNumberOfGoalsAndContexts3d


== Bugs? Doubts?

* Look for existing issues or create a new one describing your problem or doubt
* Contact the author by email
	* gabrielsr@gmail.com

